--1 :
SELECT EMPLOYEE_NUMBER , CONCAT(LAST_NAME  , FIRST_NAME) AS FULL_NAME , (YEAR(GETDATE()) - YEAR(BIRTH_DATE)) AS AGE , ( SALARY + COMMISSION ) AS NET_SALARY 
FROM EMPLOYEES 
WHERE TITLE = 'Mr.'
AND (SALARY + COMMISSION ) >= 8000 
ORDER BY HIRE_DATE DESC ;

--2 : 
SELECT * FROM PRODUCTS ;

SELECT PRODUCT_REF , PRODUCT_NAME ,  SUPPLIER_NUMBER , UNITS_ON_ORDER , UNIT_PRICE
FROM PRODUCTS 
WHERE QUANTITY LIKE '% bottles %' AND  ( SUBSTRING( PRODUCT_NAME ,3,1) = 'T' OR SUBSTRING( PRODUCT_NAME ,3,1) = 't' )  AND SUPPLIER_NUMBER IN (1,2,3) AND ( UNIT_PRICE BETWEEN 70 AND 200 ) AND  ( UNITS_ON_ORDER IS NOT NULL )  
;


--3 : 

SELECT CUSTOMERS.* 
FROM CUSTOMERS 
LEFT JOIN  SUPPLIERS 
ON CUSTOMERS.COUNTRY = SUPPLIERS.COUNTRY AND CUSTOMERS.CITY = SUPPLIERS.CITY 
WHERE SUPPLIERS.SUPPLIER_NUMBER = 1 AND RIGHT(SUPPLIERS.POSTAL_CODE , 3) = RIGHT(CUSTOMERS.POSTAL_CODE , 3);

--4 : 
SELECT * FROM ORDERS ;
SELECT * FROM ORDER_DETAILS ;

SELECT ORDER_NUMBER  , (UNIT_PRICE * QUANTITY) AS TOTAL_ORDER_AMOUNT , 
CASE 
        WHEN UNIT_PRICE * Quantity BETWEEN 0 AND 2000 THEN '0%'
        WHEN UNIT_PRICE * Quantity BETWEEN 2001 AND 10000 THEN '5%'
        WHEN UNIT_PRICE * Quantity BETWEEN 10001 AND 40000 THEN '10%'
        WHEN UNIT_PRICE * Quantity BETWEEN 40001 AND 80000 THEN '15%'
        ELSE '20%'
    END AS NewDiscountRate, 
CASE 
        WHEN ORDER_NUMBER BETWEEN 10000 AND 10999 THEN 'apply old discount rate'
        ELSE 'apply new discount rate'
    END AS DiscountRateApplicationNote

FROM ORDER_DETAILS ;




--5 :
SELECT SP.SUPPLIER_NUMBER , SP.COMPANY , SP.ADDRESS , SP.PHONE
FROM SUPPLIERS SP
JOIN PRODUCTS P 
ON SP.SUPPLIER_NUMBER = P .SUPPLIER_NUMBER
AND P.CATEGORY_CODE = 1 ;

--6 :

SELECT C.CUSTOMER_CODE
FROM CUSTOMERS C 
JOIN ORDERS O
ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD 
ON O.EMPLOYEE_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P
ON OD.PRODUCT_REF = P.PRODUCT_REF
WHERE C.CITY = 'Berlin' AND  P.CATEGORY_CODE = 3 ;


--7 :

SELECT C.CUSTOMER_CODE , C.COMPANY , C.PHONE ,C.COUNTRY ,(OD.UNIT_PRICE*OD.QUANTITY) AS TOTAL_AMOUNT 
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD 
ON O.ORDER_NUMBER = OD.ORDER_NUMBER
WHERE O.ORDER_DATE IN ('1998-04-06' , '1998-04-13' , '1998-04-20' , '1998-04-27') ;

--8 :

--the_total_number_of_products :
SELECT COUNT(PRODUCT_REF) AS TOTAL_NUMBER_OF_PRODUCTS
FROM PRODUCTS 
-- THE TOTAL NUMBER OF PRODUCTS IS EQUAL TO 50


--THE PRODUCTS ORDERED BY EACH CUSTOMER : 

SELECT C1.CUSTOMER_CODE , C1.COMPANY , C1.PHONE
FROM CUSTOMERS C1
JOIN (SELECT C.CUSTOMER_CODE , COUNT(DISTINCT OD.PRODUCT_REF) AS ORDER_PRODUCT_COUNT
FROM CUSTOMERS C
JOIN ORDERS O 
ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD 
ON O.ORDER_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P 
ON OD.PRODUCT_REF = P.PRODUCT_REF
GROUP BY C.CUSTOMER_CODE) AS JOIN_TABLE
ON C1.CUSTOMER_CODE = JOIN_TABLE.CUSTOMER_CODE
WHERE JOIN_TABLE.ORDER_PRODUCT_COUNT = 50


--9 : 

SELECT * FROM CUSTOMERS ;
SELECT * FROM ORDERS ;

SELECT O.CUSTOMER_CODE , COUNT(O.ORDER_NUMBER) AS NUMBER_OF_ORDERS 
FROM CUSTOMERS C 
JOIN ORDERS O 
ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
WHERE C.COUNTRY ='France' 
GROUP BY O.CUSTOMER_CODE ;


--10 :


DECLARE @COUNT_1996 INT ;
SET @COUNT_1996 = (SELECT COUNT(ORDER_NUMBER) AS ORDERS_IN_1996 
                    FROM ORDERS
                    WHERE YEAR(ORDER_DATE) = 1996 )

DECLARE @COUNT_1997 INT ;
SET @COUNT_1997 = (SELECT COUNT(ORDER_NUMBER) AS ORDERS_IN_1997
FROM ORDERS
WHERE YEAR(ORDER_DATE) = 1997)


DECLARE @DIFFERENCE INT ;
SET @DIFFERENCE = @COUNT_1997 - @COUNT_1996

SELECT @COUNT_1997 AS NUMBER_OF_ORDERS_IN_1997 , @COUNT_1996 AS NUMBER_OF_ORDERS_IN_1996  , @DIFFERENCE AS THE_DIFFERENCE_BETWEEN_ORDERS ;




